name: 'linting'
description: 'Linting code using ruff'
inputs:
  python-version:
    description: 'The Python version'
    required: false
    default: '3.11'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install ".[tests]"
    - name: test ruff
      shell: bash
      run: |
        ruff check --output-format=github
