name: 'pytest'
description: 'Run pytest'
inputs:
  python-version:
    description: 'The Python version'
    required: false
    default: '3.11'
  blender:
    description: 'Whether to use blender or not'
    required: false
    default: false
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[tests]"
    - name: Install Blender dependencies if desired
      if: inputs.blender == 'true'
      run: |
        pip install ".[blender]"
    - name: Test with pytest
      run: |
        pytest

