name: 'build_docs'
description: 'Build documentation using Sphinx'
inputs:
  python-version:
    description: 'The Python version'
    required: false
    default: '3.11'
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install ".[docs]"
    - name: build docs
      run: |            
          cd docs/
          make html SPHINXOPTS="-W"
